basePath: /
definitions:
  pb.GetSourceResponse:
    properties:
      source:
        $ref: '#/definitions/pb.Source'
    type: object
  pb.ListSourcesResponse:
    properties:
      sources:
        items:
          $ref: '#/definitions/pb.Source'
        type: array
    type: object
  pb.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  pb.LoginResponse:
    properties:
      meta:
        $ref: '#/definitions/pb.UserAuthMetadata'
      token:
        type: string
      type:
        type: string
    type: object
  pb.Source:
    properties:
      content:
        items:
          type: integer
        type: array
      credentials:
        items:
          type: integer
        type: array
      title:
        type: string
      typ:
        $ref: '#/definitions/pb.SourceType'
      updateParams:
        $ref: '#/definitions/pb.UpdateParams'
    type: object
  pb.SourceType:
    enum:
    - 0
    - 1
    - 2
    - 3
    - 4
    type: integer
    x-enum-varnames:
    - SourceType_UNDEFINED_SOURCE_TYPE
    - SourceType_WEB_SOURCE
    - SourceType_SINGLE_FILE
    - SourceType_ARCHIVED_FILES
    - SourceType_WITH_CREDENTIALS
  pb.UpdateParams:
    properties:
      everyPeriod:
        type: integer
      onTime:
        $ref: '#/definitions/timeofday.TimeOfDay'
    type: object
  pb.UpdateSourceRequest:
    properties:
      content:
        items:
          type: integer
        type: array
      credentials:
        items:
          type: integer
        type: array
      sourceId:
        type: integer
      title:
        type: string
      updateParams:
        $ref: '#/definitions/pb.UpdateParams'
    type: object
  pb.UserAuthMetadata:
    properties:
      roles:
        items:
          type: integer
        type: array
      userId:
        type: integer
    type: object
  timeofday.TimeOfDay:
    properties:
      hours:
        description: |-
          Hours of day in 24 hour format. Should be from 0 to 23. An API may choose
          to allow the value "24:00:00" for scenarios like business closing time.
        type: integer
      minutes:
        description: Minutes of hour of day. Must be from 0 to 59.
        type: integer
      nanos:
        description: Fractions of seconds in nanoseconds. Must be from 0 to 999,999,999.
        type: integer
      seconds:
        description: |-
          Seconds of minutes of the time. Must normally be from 0 to 59. An API may
          allow the value 60 if it allows leap-seconds.
        type: integer
    type: object
host: localhost:9000
info:
  contact: {}
  description: Diploma RAG API service documentation.
  license:
    name: MIT
    url: https://github.com/larek-tech/diploma/blob/api/LICENSE
  title: Diploma API
  version: "1.0"
paths:
  /api/v1/domain/:
    post:
      consumes:
      - application/json
      description: Creates new domain source used for RAG vector search.
      parameters:
      - description: Input data for creating source
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/pb.Source'
      produces:
      - application/json
      responses:
        "201":
          description: Source successfully created
          schema:
            $ref: '#/definitions/pb.Source'
        "400":
          description: Failed to create source
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Create new source.
      tags:
      - domain
  /api/v1/domain/{id}:
    delete:
      consumes:
      - application/json
      description: Delete domain source by ID.
      parameters:
      - description: Source ID
        in: path
        name: sourceID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: Source deleted
          schema:
            type: string
        "400":
          description: Failed to delete source
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Delete source.
      tags:
      - domain
    get:
      consumes:
      - application/json
      description: Returns information about source and its update parameters.
      parameters:
      - description: Requested source ID
        in: path
        name: sourceID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Source
          schema:
            $ref: '#/definitions/pb.GetSourceResponse'
        "400":
          description: Failed to get source
          schema:
            type: string
        "404":
          description: Source not found
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Get source.
      tags:
      - domain
    put:
      consumes:
      - application/json
      description: Update source information or params for update job.
      parameters:
      - description: Source ID
        in: path
        name: sourceID
        required: true
        type: integer
      - description: Update params
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/pb.UpdateSourceRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Source updated
          schema:
            $ref: '#/definitions/pb.Source'
        "400":
          description: Failed to update source
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Update source.
      tags:
      - domain
  /api/v1/domain/list:
    get:
      consumes:
      - application/json
      description: List sources to which user has access.
      parameters:
      - description: Pagination offset
        in: query
        name: offset
        required: true
        type: integer
      - description: Pagination limit
        in: query
        name: limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of sources
          schema:
            $ref: '#/definitions/pb.ListSourcesResponse'
        "400":
          description: Failed to list sources
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: List sources.
      tags:
      - domain
  /auth/v1/login:
    post:
      consumes:
      - application/json
      description: Authorizes user with provided credentials.
      parameters:
      - description: User credentials
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/pb.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Auth token and metadata
          schema:
            $ref: '#/definitions/pb.LoginResponse'
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: Login user.
      tags:
      - auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
