apiVersion: v1
data:
  .dockerconfigjson: base64 encoded json
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson

#kubectl create secret docker-registry regcred \
#  --docker-server=docker.registry.com \
#  --docker-username=username \
#  --docker-password=passoword \
#  --dry-run=client -o yaml