# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml/v1/model.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "ml/v1/model.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11ml/v1/model.proto\x12\x05pb.ml"e\n\nMultiQuery\x12\x15\n\ruseMultiquery\x18\x01 \x01(\x08\x12\x10\n\x08nQueryes\x18\x02 \x01(\x03\x12\x1b\n\x0equeryModelName\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x11\n\x0f_queryModelName"]\n\x08Reranker\x12\x11\n\tuseRerank\x18\x01 \x01(\x08\x12\x15\n\rrerankerModel\x18\x02 \x01(\t\x12\x19\n\x11rerankerMaxLenght\x18\x03 \x01(\x03\x12\x0c\n\x04topK\x18\x04 \x01(\x03"L\n\x07LLMMdel\x12\x11\n\tmodelName\x18\x01 \x01(\t\x12\x12\n\ntemprature\x18\x02 \x01(\x02\x12\x0c\n\x04topK\x18\x03 \x01(\x03\x12\x0c\n\x04topP\x18\x04 \x01(\x02"F\n\x0cVectorSearch\x12\x0c\n\x04topN\x18\x01 \x01(\x03\x12\x11\n\tthreshold\x18\x02 \x01(\x02\x12\x15\n\rsearchByQuery\x18\x03 \x01(\x08"\xd8\x01\n\x08Scenario\x12\'\n\ncustomType\x18\x01 \x01(\x0e\x32\x13.pb.ml.ScenarioType\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12%\n\nmultiQuery\x18\x03 \x01(\x0b\x32\x11.pb.ml.MultiQuery\x12!\n\x08reranker\x18\x04 \x01(\x0b\x32\x0f.pb.ml.Reranker\x12)\n\x0cvectorSearch\x18\x05 \x01(\x0b\x32\x13.pb.ml.VectorSearch\x12\x1d\n\x05model\x18\x06 \x01(\x0b\x32\x0e.pb.ml.LLMMdel"(\n\x05Query\x12\x0e\n\x06userId\x18\x01 \x01(\x03\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t"h\n\x13ProcessQueryRequest\x12\x1b\n\x05query\x18\x01 \x01(\x0b\x32\x0c.pb.ml.Query\x12!\n\x08scenario\x18\x02 \x01(\x0b\x32\x0f.pb.ml.Scenario\x12\x11\n\tsourceIds\x18\x03 \x03(\t"\x18\n\x05\x43hunk\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t"F\n\x14ProcessQueryResponse\x12\x1b\n\x05\x63hunk\x18\x01 \x01(\x0b\x32\x0c.pb.ml.Chunk\x12\x11\n\tsourceIds\x18\x02 \x03(\t*9\n\x0cScenarioType\x12\x16\n\x12UNDEFINED_SCENARIO\x10\x00\x12\x11\n\rSYSTEM_PROMPT\x10\x01\x42\x10Z\x0einternal/ml/pbb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "ml.v1.model_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"Z\016internal/ml/pb"
    _globals["_SCENARIOTYPE"]._serialized_start = 841
    _globals["_SCENARIOTYPE"]._serialized_end = 898
    _globals["_MULTIQUERY"]._serialized_start = 28
    _globals["_MULTIQUERY"]._serialized_end = 129
    _globals["_RERANKER"]._serialized_start = 131
    _globals["_RERANKER"]._serialized_end = 224
    _globals["_LLMMDEL"]._serialized_start = 226
    _globals["_LLMMDEL"]._serialized_end = 302
    _globals["_VECTORSEARCH"]._serialized_start = 304
    _globals["_VECTORSEARCH"]._serialized_end = 374
    _globals["_SCENARIO"]._serialized_start = 377
    _globals["_SCENARIO"]._serialized_end = 593
    _globals["_QUERY"]._serialized_start = 595
    _globals["_QUERY"]._serialized_end = 635
    _globals["_PROCESSQUERYREQUEST"]._serialized_start = 637
    _globals["_PROCESSQUERYREQUEST"]._serialized_end = 741
    _globals["_CHUNK"]._serialized_start = 743
    _globals["_CHUNK"]._serialized_end = 767
    _globals["_PROCESSQUERYRESPONSE"]._serialized_start = 769
    _globals["_PROCESSQUERYRESPONSE"]._serialized_end = 839
# @@protoc_insertion_point(module_scope)
