// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: ml/v1/model.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScenarioType int32

const (
	ScenarioType_UNDEFINED_SCENARIO ScenarioType = 0
	ScenarioType_SYSTEM_PROMPT      ScenarioType = 1
)

// Enum value maps for ScenarioType.
var (
	ScenarioType_name = map[int32]string{
		0: "UNDEFINED_SCENARIO",
		1: "SYSTEM_PROMPT",
	}
	ScenarioType_value = map[string]int32{
		"UNDEFINED_SCENARIO": 0,
		"SYSTEM_PROMPT":      1,
	}
)

func (x ScenarioType) Enum() *ScenarioType {
	p := new(ScenarioType)
	*p = x
	return p
}

func (x ScenarioType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScenarioType) Descriptor() protoreflect.EnumDescriptor {
	return file_ml_v1_model_proto_enumTypes[0].Descriptor()
}

func (ScenarioType) Type() protoreflect.EnumType {
	return &file_ml_v1_model_proto_enumTypes[0]
}

func (x ScenarioType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScenarioType.Descriptor instead.
func (ScenarioType) EnumDescriptor() ([]byte, []int) {
	return file_ml_v1_model_proto_rawDescGZIP(), []int{0}
}

type Scenario struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomType    ScenarioType           `protobuf:"varint,1,opt,name=customType,proto3,enum=ml.ScenarioType" json:"customType,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scenario) Reset() {
	*x = Scenario{}
	mi := &file_ml_v1_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scenario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scenario) ProtoMessage() {}

func (x *Scenario) ProtoReflect() protoreflect.Message {
	mi := &file_ml_v1_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scenario.ProtoReflect.Descriptor instead.
func (*Scenario) Descriptor() ([]byte, []int) {
	return file_ml_v1_model_proto_rawDescGZIP(), []int{0}
}

func (x *Scenario) GetCustomType() ScenarioType {
	if x != nil {
		return x.CustomType
	}
	return ScenarioType_UNDEFINED_SCENARIO
}

func (x *Scenario) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_ml_v1_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_ml_v1_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_ml_v1_model_proto_rawDescGZIP(), []int{1}
}

func (x *Query) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Query) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ProcessQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *Query                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Scenario      *Scenario              `protobuf:"bytes,2,opt,name=scenario,proto3" json:"scenario,omitempty"`
	DocumentIds   []string               `protobuf:"bytes,3,rep,name=documentIds,proto3" json:"documentIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessQueryRequest) Reset() {
	*x = ProcessQueryRequest{}
	mi := &file_ml_v1_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessQueryRequest) ProtoMessage() {}

func (x *ProcessQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ml_v1_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessQueryRequest.ProtoReflect.Descriptor instead.
func (*ProcessQueryRequest) Descriptor() ([]byte, []int) {
	return file_ml_v1_model_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessQueryRequest) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ProcessQueryRequest) GetScenario() *Scenario {
	if x != nil {
		return x.Scenario
	}
	return nil
}

func (x *ProcessQueryRequest) GetDocumentIds() []string {
	if x != nil {
		return x.DocumentIds
	}
	return nil
}

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_ml_v1_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_ml_v1_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_ml_v1_model_proto_rawDescGZIP(), []int{3}
}

func (x *Chunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ProcessQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         *Chunk                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	DocumentIds   []string               `protobuf:"bytes,2,rep,name=documentIds,proto3" json:"documentIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessQueryResponse) Reset() {
	*x = ProcessQueryResponse{}
	mi := &file_ml_v1_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessQueryResponse) ProtoMessage() {}

func (x *ProcessQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ml_v1_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessQueryResponse.ProtoReflect.Descriptor instead.
func (*ProcessQueryResponse) Descriptor() ([]byte, []int) {
	return file_ml_v1_model_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessQueryResponse) GetChunk() *Chunk {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *ProcessQueryResponse) GetDocumentIds() []string {
	if x != nil {
		return x.DocumentIds
	}
	return nil
}

var File_ml_v1_model_proto protoreflect.FileDescriptor

const file_ml_v1_model_proto_rawDesc = "" +
	"\n" +
	"\x11ml/v1/model.proto\x12\x02ml\"V\n" +
	"\bScenario\x120\n" +
	"\n" +
	"customType\x18\x01 \x01(\x0e2\x10.ml.ScenarioTypeR\n" +
	"customType\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"9\n" +
	"\x05Query\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x82\x01\n" +
	"\x13ProcessQueryRequest\x12\x1f\n" +
	"\x05query\x18\x01 \x01(\v2\t.ml.QueryR\x05query\x12(\n" +
	"\bscenario\x18\x02 \x01(\v2\f.ml.ScenarioR\bscenario\x12 \n" +
	"\vdocumentIds\x18\x03 \x03(\tR\vdocumentIds\"!\n" +
	"\x05Chunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"Y\n" +
	"\x14ProcessQueryResponse\x12\x1f\n" +
	"\x05chunk\x18\x01 \x01(\v2\t.ml.ChunkR\x05chunk\x12 \n" +
	"\vdocumentIds\x18\x02 \x03(\tR\vdocumentIds*9\n" +
	"\fScenarioType\x12\x16\n" +
	"\x12UNDEFINED_SCENARIO\x10\x00\x12\x11\n" +
	"\rSYSTEM_PROMPT\x10\x01B\x10Z\x0einternal/ml/pbb\x06proto3"

var (
	file_ml_v1_model_proto_rawDescOnce sync.Once
	file_ml_v1_model_proto_rawDescData []byte
)

func file_ml_v1_model_proto_rawDescGZIP() []byte {
	file_ml_v1_model_proto_rawDescOnce.Do(func() {
		file_ml_v1_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ml_v1_model_proto_rawDesc), len(file_ml_v1_model_proto_rawDesc)))
	})
	return file_ml_v1_model_proto_rawDescData
}

var file_ml_v1_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ml_v1_model_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ml_v1_model_proto_goTypes = []any{
	(ScenarioType)(0),            // 0: ml.ScenarioType
	(*Scenario)(nil),             // 1: ml.Scenario
	(*Query)(nil),                // 2: ml.Query
	(*ProcessQueryRequest)(nil),  // 3: ml.ProcessQueryRequest
	(*Chunk)(nil),                // 4: ml.Chunk
	(*ProcessQueryResponse)(nil), // 5: ml.ProcessQueryResponse
}
var file_ml_v1_model_proto_depIdxs = []int32{
	0, // 0: ml.Scenario.customType:type_name -> ml.ScenarioType
	2, // 1: ml.ProcessQueryRequest.query:type_name -> ml.Query
	1, // 2: ml.ProcessQueryRequest.scenario:type_name -> ml.Scenario
	4, // 3: ml.ProcessQueryResponse.chunk:type_name -> ml.Chunk
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ml_v1_model_proto_init() }
func file_ml_v1_model_proto_init() {
	if File_ml_v1_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ml_v1_model_proto_rawDesc), len(file_ml_v1_model_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ml_v1_model_proto_goTypes,
		DependencyIndexes: file_ml_v1_model_proto_depIdxs,
		EnumInfos:         file_ml_v1_model_proto_enumTypes,
		MessageInfos:      file_ml_v1_model_proto_msgTypes,
	}.Build()
	File_ml_v1_model_proto = out.File
	file_ml_v1_model_proto_goTypes = nil
	file_ml_v1_model_proto_depIdxs = nil
}
