// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: ml/v1/service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_ml_v1_service_proto protoreflect.FileDescriptor

const file_ml_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x13ml/v1/service.proto\x12\x05pb.ml\x1a\x11ml/v1/model.proto2X\n" +
	"\tMLService\x12K\n" +
	"\fProcessQuery\x12\x1a.pb.ml.ProcessQueryRequest\x1a\x1b.pb.ml.ProcessQueryResponse\"\x000\x01B\x12Z\x10./internal/ml/pbb\x06proto3"

var file_ml_v1_service_proto_goTypes = []any{
	(*ProcessQueryRequest)(nil),  // 0: pb.ml.ProcessQueryRequest
	(*ProcessQueryResponse)(nil), // 1: pb.ml.ProcessQueryResponse
}
var file_ml_v1_service_proto_depIdxs = []int32{
	0, // 0: pb.ml.MLService.ProcessQuery:input_type -> pb.ml.ProcessQueryRequest
	1, // 1: pb.ml.MLService.ProcessQuery:output_type -> pb.ml.ProcessQueryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ml_v1_service_proto_init() }
func file_ml_v1_service_proto_init() {
	if File_ml_v1_service_proto != nil {
		return
	}
	file_ml_v1_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ml_v1_service_proto_rawDesc), len(file_ml_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ml_v1_service_proto_goTypes,
		DependencyIndexes: file_ml_v1_service_proto_depIdxs,
	}.Build()
	File_ml_v1_service_proto = out.File
	file_ml_v1_service_proto_goTypes = nil
	file_ml_v1_service_proto_depIdxs = nil
}
