log_level: "debug"
server:
  grpc_port: 9002
jaeger:
  host: "jaeger"
  port: 4318
postgres:
  user: "pguser"
  password: "pgpass"
  host: "pg"
  db: "dev"
  ssl: false
  port: 5433
  retry_timeout: 5
ml_service:
  host: ml
  port: 8888
