// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: data/v1/model.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VectorSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	SourceIds     []string               `protobuf:"bytes,2,rep,name=sourceIds,proto3" json:"sourceIds,omitempty"`
	TopK          uint64                 `protobuf:"varint,3,opt,name=topK,proto3" json:"topK,omitempty"`
	Threshold     float32                `protobuf:"fixed32,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	UseQuestions  bool                   `protobuf:"varint,5,opt,name=useQuestions,proto3" json:"useQuestions,omitempty"` // hypothetical questions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorSearchRequest) Reset() {
	*x = VectorSearchRequest{}
	mi := &file_data_v1_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorSearchRequest) ProtoMessage() {}

func (x *VectorSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_data_v1_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorSearchRequest.ProtoReflect.Descriptor instead.
func (*VectorSearchRequest) Descriptor() ([]byte, []int) {
	return file_data_v1_model_proto_rawDescGZIP(), []int{0}
}

func (x *VectorSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *VectorSearchRequest) GetSourceIds() []string {
	if x != nil {
		return x.SourceIds
	}
	return nil
}

func (x *VectorSearchRequest) GetTopK() uint64 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *VectorSearchRequest) GetThreshold() float32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *VectorSearchRequest) GetUseQuestions() bool {
	if x != nil {
		return x.UseQuestions
	}
	return false
}

type DocumentChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Index         int64                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"` // encoded json<any,any>
	Similarity    float32                `protobuf:"fixed32,5,opt,name=similarity,proto3" json:"similarity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentChunk) Reset() {
	*x = DocumentChunk{}
	mi := &file_data_v1_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentChunk) ProtoMessage() {}

func (x *DocumentChunk) ProtoReflect() protoreflect.Message {
	mi := &file_data_v1_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentChunk.ProtoReflect.Descriptor instead.
func (*DocumentChunk) Descriptor() ([]byte, []int) {
	return file_data_v1_model_proto_rawDescGZIP(), []int{1}
}

func (x *DocumentChunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocumentChunk) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DocumentChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DocumentChunk) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DocumentChunk) GetSimilarity() float32 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

type VectorSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunks        []*DocumentChunk       `protobuf:"bytes,1,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorSearchResponse) Reset() {
	*x = VectorSearchResponse{}
	mi := &file_data_v1_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorSearchResponse) ProtoMessage() {}

func (x *VectorSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_data_v1_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorSearchResponse.ProtoReflect.Descriptor instead.
func (*VectorSearchResponse) Descriptor() ([]byte, []int) {
	return file_data_v1_model_proto_rawDescGZIP(), []int{2}
}

func (x *VectorSearchResponse) GetChunks() []*DocumentChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

var File_data_v1_model_proto protoreflect.FileDescriptor

const file_data_v1_model_proto_rawDesc = "" +
	"\n" +
	"\x13data/v1/model.proto\x12\adata.v1\"\x9f\x01\n" +
	"\x13VectorSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1c\n" +
	"\tsourceIds\x18\x02 \x03(\tR\tsourceIds\x12\x12\n" +
	"\x04topK\x18\x03 \x01(\x04R\x04topK\x12\x1c\n" +
	"\tthreshold\x18\x04 \x01(\x02R\tthreshold\x12\"\n" +
	"\fuseQuestions\x18\x05 \x01(\bR\fuseQuestions\"\x8b\x01\n" +
	"\rDocumentChunk\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x03R\x05index\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\fR\bmetadata\x12\x1e\n" +
	"\n" +
	"similarity\x18\x05 \x01(\x02R\n" +
	"similarity\"F\n" +
	"\x14VectorSearchResponse\x12.\n" +
	"\x06chunks\x18\x01 \x03(\v2\x16.data.v1.DocumentChunkR\x06chunksB\x12Z\x10internal/data/pbb\x06proto3"

var (
	file_data_v1_model_proto_rawDescOnce sync.Once
	file_data_v1_model_proto_rawDescData []byte
)

func file_data_v1_model_proto_rawDescGZIP() []byte {
	file_data_v1_model_proto_rawDescOnce.Do(func() {
		file_data_v1_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_v1_model_proto_rawDesc), len(file_data_v1_model_proto_rawDesc)))
	})
	return file_data_v1_model_proto_rawDescData
}

var file_data_v1_model_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_data_v1_model_proto_goTypes = []any{
	(*VectorSearchRequest)(nil),  // 0: data.v1.VectorSearchRequest
	(*DocumentChunk)(nil),        // 1: data.v1.DocumentChunk
	(*VectorSearchResponse)(nil), // 2: data.v1.VectorSearchResponse
}
var file_data_v1_model_proto_depIdxs = []int32{
	1, // 0: data.v1.VectorSearchResponse.chunks:type_name -> data.v1.DocumentChunk
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_data_v1_model_proto_init() }
func file_data_v1_model_proto_init() {
	if File_data_v1_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_v1_model_proto_rawDesc), len(file_data_v1_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_v1_model_proto_goTypes,
		DependencyIndexes: file_data_v1_model_proto_depIdxs,
		MessageInfos:      file_data_v1_model_proto_msgTypes,
	}.Build()
	File_data_v1_model_proto = out.File
	file_data_v1_model_proto_goTypes = nil
	file_data_v1_model_proto_depIdxs = nil
}
