// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: data/v1/service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_data_v1_service_proto protoreflect.FileDescriptor

const file_data_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x15data/v1/service.proto\x12\adata.v1\x1a\x13data/v1/model.proto2\xa1\x01\n" +
	"\vDataService\x12M\n" +
	"\fVectorSearch\x12\x1c.data.v1.VectorSearchRequest\x1a\x1d.data.v1.VectorSearchResponse\"\x00\x12C\n" +
	"\fGetDocuments\x12\x17.data.v1.GetDocumentsIn\x1a\x18.data.v1.GetDocumentsOut\"\x00B\x12Z\x10internal/data/pbb\x06proto3"

var file_data_v1_service_proto_goTypes = []any{
	(*VectorSearchRequest)(nil),  // 0: data.v1.VectorSearchRequest
	(*GetDocumentsIn)(nil),       // 1: data.v1.GetDocumentsIn
	(*VectorSearchResponse)(nil), // 2: data.v1.VectorSearchResponse
	(*GetDocumentsOut)(nil),      // 3: data.v1.GetDocumentsOut
}
var file_data_v1_service_proto_depIdxs = []int32{
	0, // 0: data.v1.DataService.VectorSearch:input_type -> data.v1.VectorSearchRequest
	1, // 1: data.v1.DataService.GetDocuments:input_type -> data.v1.GetDocumentsIn
	2, // 2: data.v1.DataService.VectorSearch:output_type -> data.v1.VectorSearchResponse
	3, // 3: data.v1.DataService.GetDocuments:output_type -> data.v1.GetDocumentsOut
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_v1_service_proto_init() }
func file_data_v1_service_proto_init() {
	if File_data_v1_service_proto != nil {
		return
	}
	file_data_v1_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_v1_service_proto_rawDesc), len(file_data_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_data_v1_service_proto_goTypes,
		DependencyIndexes: file_data_v1_service_proto_depIdxs,
	}.Build()
	File_data_v1_service_proto = out.File
	file_data_v1_service_proto_goTypes = nil
	file_data_v1_service_proto_depIdxs = nil
}
