// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/v1/common_model.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_domain_v1_common_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_common_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_domain_v1_common_model_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PermittedUsers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    int64                  `protobuf:"varint,1,opt,name=resourceId,proto3" json:"resourceId,omitempty"`
	UserIds       []int64                `protobuf:"varint,2,rep,packed,name=userIds,proto3" json:"userIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermittedUsers) Reset() {
	*x = PermittedUsers{}
	mi := &file_domain_v1_common_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermittedUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermittedUsers) ProtoMessage() {}

func (x *PermittedUsers) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_common_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermittedUsers.ProtoReflect.Descriptor instead.
func (*PermittedUsers) Descriptor() ([]byte, []int) {
	return file_domain_v1_common_model_proto_rawDescGZIP(), []int{1}
}

func (x *PermittedUsers) GetResourceId() int64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *PermittedUsers) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type PermittedRoles struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    int64                  `protobuf:"varint,1,opt,name=resourceId,proto3" json:"resourceId,omitempty"`
	RoleIds       []int64                `protobuf:"varint,2,rep,packed,name=roleIds,proto3" json:"roleIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermittedRoles) Reset() {
	*x = PermittedRoles{}
	mi := &file_domain_v1_common_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermittedRoles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermittedRoles) ProtoMessage() {}

func (x *PermittedRoles) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_common_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermittedRoles.ProtoReflect.Descriptor instead.
func (*PermittedRoles) Descriptor() ([]byte, []int) {
	return file_domain_v1_common_model_proto_rawDescGZIP(), []int{2}
}

func (x *PermittedRoles) GetResourceId() int64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *PermittedRoles) GetRoleIds() []int64 {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

type GetResourcePermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    int64                  `protobuf:"varint,1,opt,name=resourceId,proto3" json:"resourceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourcePermissionsRequest) Reset() {
	*x = GetResourcePermissionsRequest{}
	mi := &file_domain_v1_common_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourcePermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourcePermissionsRequest) ProtoMessage() {}

func (x *GetResourcePermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_common_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourcePermissionsRequest.ProtoReflect.Descriptor instead.
func (*GetResourcePermissionsRequest) Descriptor() ([]byte, []int) {
	return file_domain_v1_common_model_proto_rawDescGZIP(), []int{3}
}

func (x *GetResourcePermissionsRequest) GetResourceId() int64 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

var File_domain_v1_common_model_proto protoreflect.FileDescriptor

const file_domain_v1_common_model_proto_rawDesc = "" +
	"\n" +
	"\x1cdomain/v1/common_model.proto\x12\tdomain.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x128\n" +
	"\tcreatedAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"J\n" +
	"\x0ePermittedUsers\x12\x1e\n" +
	"\n" +
	"resourceId\x18\x01 \x01(\x03R\n" +
	"resourceId\x12\x18\n" +
	"\auserIds\x18\x02 \x03(\x03R\auserIds\"J\n" +
	"\x0ePermittedRoles\x12\x1e\n" +
	"\n" +
	"resourceId\x18\x01 \x01(\x03R\n" +
	"resourceId\x12\x18\n" +
	"\aroleIds\x18\x02 \x03(\x03R\aroleIds\"?\n" +
	"\x1dGetResourcePermissionsRequest\x12\x1e\n" +
	"\n" +
	"resourceId\x18\x01 \x01(\x03R\n" +
	"resourceIdB\x14Z\x12internal/domain/pbb\x06proto3"

var (
	file_domain_v1_common_model_proto_rawDescOnce sync.Once
	file_domain_v1_common_model_proto_rawDescData []byte
)

func file_domain_v1_common_model_proto_rawDescGZIP() []byte {
	file_domain_v1_common_model_proto_rawDescOnce.Do(func() {
		file_domain_v1_common_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_v1_common_model_proto_rawDesc), len(file_domain_v1_common_model_proto_rawDesc)))
	})
	return file_domain_v1_common_model_proto_rawDescData
}

var file_domain_v1_common_model_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_domain_v1_common_model_proto_goTypes = []any{
	(*User)(nil),                          // 0: domain.v1.User
	(*PermittedUsers)(nil),                // 1: domain.v1.PermittedUsers
	(*PermittedRoles)(nil),                // 2: domain.v1.PermittedRoles
	(*GetResourcePermissionsRequest)(nil), // 3: domain.v1.GetResourcePermissionsRequest
	(*timestamppb.Timestamp)(nil),         // 4: google.protobuf.Timestamp
}
var file_domain_v1_common_model_proto_depIdxs = []int32{
	4, // 0: domain.v1.User.createdAt:type_name -> google.protobuf.Timestamp
	4, // 1: domain.v1.User.updatedAt:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_domain_v1_common_model_proto_init() }
func file_domain_v1_common_model_proto_init() {
	if File_domain_v1_common_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_v1_common_model_proto_rawDesc), len(file_domain_v1_common_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_v1_common_model_proto_goTypes,
		DependencyIndexes: file_domain_v1_common_model_proto_depIdxs,
		MessageInfos:      file_domain_v1_common_model_proto_msgTypes,
	}.Build()
	File_domain_v1_common_model_proto = out.File
	file_domain_v1_common_model_proto_goTypes = nil
	file_domain_v1_common_model_proto_depIdxs = nil
}
