// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/v1/scenario_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_domain_v1_scenario_service_proto protoreflect.FileDescriptor

const file_domain_v1_scenario_service_proto_rawDesc = "" +
	"\n" +
	" domain/v1/scenario_service.proto\x12\tdomain.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1edomain/v1/scenario_model.proto\x1a\x11ml/v1/model.proto2\x93\x03\n" +
	"\x0fScenarioService\x12E\n" +
	"\x0eCreateScenario\x12 .domain.v1.CreateScenarioRequest\x1a\x0f.pb.ml.Scenario\"\x00\x12N\n" +
	"\vGetScenario\x12\x1d.domain.v1.GetScenarioRequest\x1a\x1e.domain.v1.GetScenarioResponse\"\x00\x12E\n" +
	"\x0eUpdateScenario\x12 .domain.v1.UpdateScenarioRequest\x1a\x0f.pb.ml.Scenario\"\x00\x12L\n" +
	"\x0eDeleteScenario\x12 .domain.v1.DeleteScenarioRequest\x1a\x16.google.protobuf.Empty\"\x00\x12T\n" +
	"\rListScenarios\x12\x1f.domain.v1.ListScenariosRequest\x1a .domain.v1.ListScenariosResponse\"\x00B\x14Z\x12internal/domain/pbb\x06proto3"

var file_domain_v1_scenario_service_proto_goTypes = []any{
	(*CreateScenarioRequest)(nil), // 0: domain.v1.CreateScenarioRequest
	(*GetScenarioRequest)(nil),    // 1: domain.v1.GetScenarioRequest
	(*UpdateScenarioRequest)(nil), // 2: domain.v1.UpdateScenarioRequest
	(*DeleteScenarioRequest)(nil), // 3: domain.v1.DeleteScenarioRequest
	(*ListScenariosRequest)(nil),  // 4: domain.v1.ListScenariosRequest
	(*Scenario)(nil),              // 5: pb.ml.Scenario
	(*GetScenarioResponse)(nil),   // 6: domain.v1.GetScenarioResponse
	(*emptypb.Empty)(nil),         // 7: google.protobuf.Empty
	(*ListScenariosResponse)(nil), // 8: domain.v1.ListScenariosResponse
}
var file_domain_v1_scenario_service_proto_depIdxs = []int32{
	0, // 0: domain.v1.ScenarioService.CreateScenario:input_type -> domain.v1.CreateScenarioRequest
	1, // 1: domain.v1.ScenarioService.GetScenario:input_type -> domain.v1.GetScenarioRequest
	2, // 2: domain.v1.ScenarioService.UpdateScenario:input_type -> domain.v1.UpdateScenarioRequest
	3, // 3: domain.v1.ScenarioService.DeleteScenario:input_type -> domain.v1.DeleteScenarioRequest
	4, // 4: domain.v1.ScenarioService.ListScenarios:input_type -> domain.v1.ListScenariosRequest
	5, // 5: domain.v1.ScenarioService.CreateScenario:output_type -> pb.ml.Scenario
	6, // 6: domain.v1.ScenarioService.GetScenario:output_type -> domain.v1.GetScenarioResponse
	5, // 7: domain.v1.ScenarioService.UpdateScenario:output_type -> pb.ml.Scenario
	7, // 8: domain.v1.ScenarioService.DeleteScenario:output_type -> google.protobuf.Empty
	8, // 9: domain.v1.ScenarioService.ListScenarios:output_type -> domain.v1.ListScenariosResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_domain_v1_scenario_service_proto_init() }
func file_domain_v1_scenario_service_proto_init() {
	if File_domain_v1_scenario_service_proto != nil {
		return
	}
	file_domain_v1_scenario_model_proto_init()
	file_ml_v1_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_v1_scenario_service_proto_rawDesc), len(file_domain_v1_scenario_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_domain_v1_scenario_service_proto_goTypes,
		DependencyIndexes: file_domain_v1_scenario_service_proto_depIdxs,
	}.Build()
	File_domain_v1_scenario_service_proto = out.File
	file_domain_v1_scenario_service_proto_goTypes = nil
	file_domain_v1_scenario_service_proto_depIdxs = nil
}
