// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/v1/source_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_domain_v1_source_service_proto protoreflect.FileDescriptor

const file_domain_v1_source_service_proto_rawDesc = "" +
	"\n" +
	"\x1edomain/v1/source_service.proto\x12\tdomain.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cdomain/v1/source_model.proto\x1a\x1cdomain/v1/common_model.proto2\xd5\x05\n" +
	"\rSourceService\x12C\n" +
	"\fCreateSource\x12\x1e.domain.v1.CreateSourceRequest\x1a\x11.domain.v1.Source\"\x00\x12H\n" +
	"\tGetSource\x12\x1b.domain.v1.GetSourceRequest\x1a\x1c.domain.v1.GetSourceResponse\"\x00\x12C\n" +
	"\fUpdateSource\x12\x1e.domain.v1.UpdateSourceRequest\x1a\x11.domain.v1.Source\"\x00\x12H\n" +
	"\fDeleteSource\x12\x1e.domain.v1.DeleteSourceRequest\x1a\x16.google.protobuf.Empty\"\x00\x12N\n" +
	"\vListSources\x12\x1d.domain.v1.ListSourcesRequest\x1a\x1e.domain.v1.ListSourcesResponse\"\x00\x12Z\n" +
	"\x11GetPermittedUsers\x12(.domain.v1.GetResourcePermissionsRequest\x1a\x19.domain.v1.PermittedUsers\"\x00\x12N\n" +
	"\x14UpdatePermittedUsers\x12\x19.domain.v1.PermittedUsers\x1a\x19.domain.v1.PermittedUsers\"\x00\x12Z\n" +
	"\x11GetPermittedRoles\x12(.domain.v1.GetResourcePermissionsRequest\x1a\x19.domain.v1.PermittedRoles\"\x00\x12N\n" +
	"\x14UpdatePermittedRoles\x12\x19.domain.v1.PermittedRoles\x1a\x19.domain.v1.PermittedRoles\"\x00B\x14Z\x12internal/domain/pbb\x06proto3"

var file_domain_v1_source_service_proto_goTypes = []any{
	(*CreateSourceRequest)(nil),           // 0: domain.v1.CreateSourceRequest
	(*GetSourceRequest)(nil),              // 1: domain.v1.GetSourceRequest
	(*UpdateSourceRequest)(nil),           // 2: domain.v1.UpdateSourceRequest
	(*DeleteSourceRequest)(nil),           // 3: domain.v1.DeleteSourceRequest
	(*ListSourcesRequest)(nil),            // 4: domain.v1.ListSourcesRequest
	(*GetResourcePermissionsRequest)(nil), // 5: domain.v1.GetResourcePermissionsRequest
	(*PermittedUsers)(nil),                // 6: domain.v1.PermittedUsers
	(*PermittedRoles)(nil),                // 7: domain.v1.PermittedRoles
	(*Source)(nil),                        // 8: domain.v1.Source
	(*GetSourceResponse)(nil),             // 9: domain.v1.GetSourceResponse
	(*emptypb.Empty)(nil),                 // 10: google.protobuf.Empty
	(*ListSourcesResponse)(nil),           // 11: domain.v1.ListSourcesResponse
}
var file_domain_v1_source_service_proto_depIdxs = []int32{
	0,  // 0: domain.v1.SourceService.CreateSource:input_type -> domain.v1.CreateSourceRequest
	1,  // 1: domain.v1.SourceService.GetSource:input_type -> domain.v1.GetSourceRequest
	2,  // 2: domain.v1.SourceService.UpdateSource:input_type -> domain.v1.UpdateSourceRequest
	3,  // 3: domain.v1.SourceService.DeleteSource:input_type -> domain.v1.DeleteSourceRequest
	4,  // 4: domain.v1.SourceService.ListSources:input_type -> domain.v1.ListSourcesRequest
	5,  // 5: domain.v1.SourceService.GetPermittedUsers:input_type -> domain.v1.GetResourcePermissionsRequest
	6,  // 6: domain.v1.SourceService.UpdatePermittedUsers:input_type -> domain.v1.PermittedUsers
	5,  // 7: domain.v1.SourceService.GetPermittedRoles:input_type -> domain.v1.GetResourcePermissionsRequest
	7,  // 8: domain.v1.SourceService.UpdatePermittedRoles:input_type -> domain.v1.PermittedRoles
	8,  // 9: domain.v1.SourceService.CreateSource:output_type -> domain.v1.Source
	9,  // 10: domain.v1.SourceService.GetSource:output_type -> domain.v1.GetSourceResponse
	8,  // 11: domain.v1.SourceService.UpdateSource:output_type -> domain.v1.Source
	10, // 12: domain.v1.SourceService.DeleteSource:output_type -> google.protobuf.Empty
	11, // 13: domain.v1.SourceService.ListSources:output_type -> domain.v1.ListSourcesResponse
	6,  // 14: domain.v1.SourceService.GetPermittedUsers:output_type -> domain.v1.PermittedUsers
	6,  // 15: domain.v1.SourceService.UpdatePermittedUsers:output_type -> domain.v1.PermittedUsers
	7,  // 16: domain.v1.SourceService.GetPermittedRoles:output_type -> domain.v1.PermittedRoles
	7,  // 17: domain.v1.SourceService.UpdatePermittedRoles:output_type -> domain.v1.PermittedRoles
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_domain_v1_source_service_proto_init() }
func file_domain_v1_source_service_proto_init() {
	if File_domain_v1_source_service_proto != nil {
		return
	}
	file_domain_v1_source_model_proto_init()
	file_domain_v1_common_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_v1_source_service_proto_rawDesc), len(file_domain_v1_source_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_domain_v1_source_service_proto_goTypes,
		DependencyIndexes: file_domain_v1_source_service_proto_depIdxs,
	}.Build()
	File_domain_v1_source_service_proto = out.File
	file_domain_v1_source_service_proto_goTypes = nil
	file_domain_v1_source_service_proto_depIdxs = nil
}
