services:
  postgres:
    build:
      context: ../data
      dockerfile: docker/postgres.Dockerfile
    container_name: postgres_local
    restart: unless-stopped
    env_file:
      - configs/data.migrator.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrator:
    build:
      context: ../data
      dockerfile: docker/migrator.Dockerfile
    container_name: migrator_local
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
        - configs/data.migrator.env

  crawler:
    build:
      context: ../data
      dockerfile: docker/crawler.Dockerfile
    container_name: crawler_local
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
        - configs/data.crawler.env
    ports:
      - "9091:9090"
      - "9998:8080"
      - "50051:50051"
  parser:
    build:
      context: ../data
      dockerfile: docker/parser.Dockerfile
    container_name: parser_local
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
        - configs/data.parser.env
    ports:
      - "9999:8081"
      - "9095:9090"



volumes:
  postgres_data:
