volumes:
  jaeger_data:
  grafana_data:
  grafana_dashboards:

services:
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    volumes:
      - 'jaeger_data:/tmp'
    ports:
      - '5775:5775'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '14250:14250'
      - '9411:9411'
      - '4317:4317'
      - '4318:4318'
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v2.28.0
    environment:
      - PROM_CONFIG_B64=${PROM_CONFIG_B64}
    entrypoint: ["/bin/sh", "-c", "echo $PROM_CONFIG_B64 | base64 -d > /etc/prometheus/prometheus.yaml && exec prometheus --config.file=/etc/prometheus/prometheus.yaml"]
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_dashboards:/var/lib/grafana/dashboards