// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: auth/v1/service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_auth_v1_service_proto protoreflect.FileDescriptor

const file_auth_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x15auth/v1/service.proto\x12\aauth.v1\x1a\x13auth/v1/model.proto2\x8a\x01\n" +
	"\vAuthService\x128\n" +
	"\x05Login\x12\x15.auth.v1.LoginRequest\x1a\x16.auth.v1.LoginResponse\"\x00\x12A\n" +
	"\bValidate\x12\x18.auth.v1.ValidateRequest\x1a\x19.auth.v1.ValidateResponse\"\x00B\x12Z\x10internal/auth/pbb\x06proto3"

var file_auth_v1_service_proto_goTypes = []any{
	(*LoginRequest)(nil),     // 0: auth.v1.LoginRequest
	(*ValidateRequest)(nil),  // 1: auth.v1.ValidateRequest
	(*LoginResponse)(nil),    // 2: auth.v1.LoginResponse
	(*ValidateResponse)(nil), // 3: auth.v1.ValidateResponse
}
var file_auth_v1_service_proto_depIdxs = []int32{
	0, // 0: auth.v1.AuthService.Login:input_type -> auth.v1.LoginRequest
	1, // 1: auth.v1.AuthService.Validate:input_type -> auth.v1.ValidateRequest
	2, // 2: auth.v1.AuthService.Login:output_type -> auth.v1.LoginResponse
	3, // 3: auth.v1.AuthService.Validate:output_type -> auth.v1.ValidateResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_v1_service_proto_init() }
func file_auth_v1_service_proto_init() {
	if File_auth_v1_service_proto != nil {
		return
	}
	file_auth_v1_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_service_proto_rawDesc), len(file_auth_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_service_proto_goTypes,
		DependencyIndexes: file_auth_v1_service_proto_depIdxs,
	}.Build()
	File_auth_v1_service_proto = out.File
	file_auth_v1_service_proto_goTypes = nil
	file_auth_v1_service_proto_depIdxs = nil
}
