log_level: "debug"
server:
  grpc_port: 9003
jaeger:
  host: "jaeger"
  port: 4318
postgres:
  user: "pguser"
  password: "pgpass"
  host: "postgres"
  db: "dev"
  ssl: false
  port: 5432
  retry_timeout: 5
kafka:
  offset_newest: true
  brokers:
    - host: "kafka"
      port: 29092
  topics:
    - name: "source"
      partitions: 1
    - name: "status"
      partitions: 1
