// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/v1/admin_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_domain_v1_admin_service_proto protoreflect.FileDescriptor

const file_domain_v1_admin_service_proto_rawDesc = "" +
	"\n" +
	"\x1ddomain/v1/admin_service.proto\x12\tdomain.v1\x1a\x1bdomain/v1/admin_model.proto2X\n" +
	"\fAdminService\x12H\n" +
	"\tListUsers\x12\x1b.domain.v1.ListUsersRequest\x1a\x1c.domain.v1.ListUsersResponse\"\x00B\x14Z\x12internal/domain/pbb\x06proto3"

var file_domain_v1_admin_service_proto_goTypes = []any{
	(*ListUsersRequest)(nil),  // 0: domain.v1.ListUsersRequest
	(*ListUsersResponse)(nil), // 1: domain.v1.ListUsersResponse
}
var file_domain_v1_admin_service_proto_depIdxs = []int32{
	0, // 0: domain.v1.AdminService.ListUsers:input_type -> domain.v1.ListUsersRequest
	1, // 1: domain.v1.AdminService.ListUsers:output_type -> domain.v1.ListUsersResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_domain_v1_admin_service_proto_init() }
func file_domain_v1_admin_service_proto_init() {
	if File_domain_v1_admin_service_proto != nil {
		return
	}
	file_domain_v1_admin_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_v1_admin_service_proto_rawDesc), len(file_domain_v1_admin_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_domain_v1_admin_service_proto_goTypes,
		DependencyIndexes: file_domain_v1_admin_service_proto_depIdxs,
	}.Build()
	File_domain_v1_admin_service_proto = out.File
	file_domain_v1_admin_service_proto_goTypes = nil
	file_domain_v1_admin_service_proto_depIdxs = nil
}
