// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/v1/model.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SourceType int32

const (
	SourceType_UNDEFINED_SOURCE_TYPE SourceType = 0
	SourceType_WEB_SOURCE            SourceType = 1
	SourceType_SINGLE_FILE           SourceType = 2
	SourceType_ARCHIVED_FILES        SourceType = 3
	SourceType_WITH_CREDENTIALS      SourceType = 4
)

// Enum value maps for SourceType.
var (
	SourceType_name = map[int32]string{
		0: "UNDEFINED_SOURCE_TYPE",
		1: "WEB_SOURCE",
		2: "SINGLE_FILE",
		3: "ARCHIVED_FILES",
		4: "WITH_CREDENTIALS",
	}
	SourceType_value = map[string]int32{
		"UNDEFINED_SOURCE_TYPE": 0,
		"WEB_SOURCE":            1,
		"SINGLE_FILE":           2,
		"ARCHIVED_FILES":        3,
		"WITH_CREDENTIALS":      4,
	}
)

func (x SourceType) Enum() *SourceType {
	p := new(SourceType)
	*p = x
	return p
}

func (x SourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_domain_v1_model_proto_enumTypes[0].Descriptor()
}

func (SourceType) Type() protoreflect.EnumType {
	return &file_domain_v1_model_proto_enumTypes[0]
}

func (x SourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourceType.Descriptor instead.
func (SourceType) EnumDescriptor() ([]byte, []int) {
	return file_domain_v1_model_proto_rawDescGZIP(), []int{0}
}

type Source struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Typ           SourceType             `protobuf:"varint,3,opt,name=typ,proto3,enum=domain.v1.SourceType" json:"typ,omitempty"`
	UpdateParams  *UpdateParams          `protobuf:"bytes,4,opt,name=updateParams,proto3,oneof" json:"updateParams,omitempty"`
	Credentials   []byte                 `protobuf:"bytes,5,opt,name=credentials,proto3,oneof" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_domain_v1_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_domain_v1_model_proto_rawDescGZIP(), []int{0}
}

func (x *Source) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Source) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Source) GetTyp() SourceType {
	if x != nil {
		return x.Typ
	}
	return SourceType_UNDEFINED_SOURCE_TYPE
}

func (x *Source) GetUpdateParams() *UpdateParams {
	if x != nil {
		return x.UpdateParams
	}
	return nil
}

func (x *Source) GetCredentials() []byte {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type UpdateParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EveryPeriod   int64                  `protobuf:"varint,1,opt,name=everyPeriod,proto3" json:"everyPeriod,omitempty"`
	OnTime        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=onTime,proto3" json:"onTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateParams) Reset() {
	*x = UpdateParams{}
	mi := &file_domain_v1_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateParams) ProtoMessage() {}

func (x *UpdateParams) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateParams.ProtoReflect.Descriptor instead.
func (*UpdateParams) Descriptor() ([]byte, []int) {
	return file_domain_v1_model_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateParams) GetEveryPeriod() int64 {
	if x != nil {
		return x.EveryPeriod
	}
	return 0
}

func (x *UpdateParams) GetOnTime() *timestamppb.Timestamp {
	if x != nil {
		return x.OnTime
	}
	return nil
}

type CreateSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Source        *Source                `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSourceRequest) Reset() {
	*x = CreateSourceRequest{}
	mi := &file_domain_v1_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSourceRequest) ProtoMessage() {}

func (x *CreateSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSourceRequest.ProtoReflect.Descriptor instead.
func (*CreateSourceRequest) Descriptor() ([]byte, []int) {
	return file_domain_v1_model_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSourceRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateSourceRequest) GetSource() *Source {
	if x != nil {
		return x.Source
	}
	return nil
}

type CreateSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      int64                  `protobuf:"varint,1,opt,name=sourceId,proto3" json:"sourceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSourceResponse) Reset() {
	*x = CreateSourceResponse{}
	mi := &file_domain_v1_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSourceResponse) ProtoMessage() {}

func (x *CreateSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSourceResponse.ProtoReflect.Descriptor instead.
func (*CreateSourceResponse) Descriptor() ([]byte, []int) {
	return file_domain_v1_model_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSourceResponse) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

type GetSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	SourceId      int64                  `protobuf:"varint,2,opt,name=sourceId,proto3" json:"sourceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSourceRequest) Reset() {
	*x = GetSourceRequest{}
	mi := &file_domain_v1_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSourceRequest) ProtoMessage() {}

func (x *GetSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSourceRequest.ProtoReflect.Descriptor instead.
func (*GetSourceRequest) Descriptor() ([]byte, []int) {
	return file_domain_v1_model_proto_rawDescGZIP(), []int{4}
}

func (x *GetSourceRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetSourceRequest) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

type GetSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        *Source                `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSourceResponse) Reset() {
	*x = GetSourceResponse{}
	mi := &file_domain_v1_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSourceResponse) ProtoMessage() {}

func (x *GetSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSourceResponse.ProtoReflect.Descriptor instead.
func (*GetSourceResponse) Descriptor() ([]byte, []int) {
	return file_domain_v1_model_proto_rawDescGZIP(), []int{5}
}

func (x *GetSourceResponse) GetSource() *Source {
	if x != nil {
		return x.Source
	}
	return nil
}

type UpdateSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	SourceId      int64                  `protobuf:"varint,2,opt,name=sourceId,proto3" json:"sourceId,omitempty"`
	Title         *string                `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Content       []byte                 `protobuf:"bytes,4,opt,name=content,proto3,oneof" json:"content,omitempty"`
	UpdateParams  *UpdateParams          `protobuf:"bytes,5,opt,name=updateParams,proto3,oneof" json:"updateParams,omitempty"`
	Credentials   []byte                 `protobuf:"bytes,6,opt,name=credentials,proto3,oneof" json:"credentials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSourceRequest) Reset() {
	*x = UpdateSourceRequest{}
	mi := &file_domain_v1_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSourceRequest) ProtoMessage() {}

func (x *UpdateSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSourceRequest.ProtoReflect.Descriptor instead.
func (*UpdateSourceRequest) Descriptor() ([]byte, []int) {
	return file_domain_v1_model_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSourceRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateSourceRequest) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

func (x *UpdateSourceRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateSourceRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UpdateSourceRequest) GetUpdateParams() *UpdateParams {
	if x != nil {
		return x.UpdateParams
	}
	return nil
}

func (x *UpdateSourceRequest) GetCredentials() []byte {
	if x != nil {
		return x.Credentials
	}
	return nil
}

type DeleteSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	SourceId      int64                  `protobuf:"varint,2,opt,name=sourceId,proto3" json:"sourceId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSourceRequest) Reset() {
	*x = DeleteSourceRequest{}
	mi := &file_domain_v1_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSourceRequest) ProtoMessage() {}

func (x *DeleteSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSourceRequest.ProtoReflect.Descriptor instead.
func (*DeleteSourceRequest) Descriptor() ([]byte, []int) {
	return file_domain_v1_model_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteSourceRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteSourceRequest) GetSourceId() int64 {
	if x != nil {
		return x.SourceId
	}
	return 0
}

type ListSourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSourcesRequest) Reset() {
	*x = ListSourcesRequest{}
	mi := &file_domain_v1_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSourcesRequest) ProtoMessage() {}

func (x *ListSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSourcesRequest.ProtoReflect.Descriptor instead.
func (*ListSourcesRequest) Descriptor() ([]byte, []int) {
	return file_domain_v1_model_proto_rawDescGZIP(), []int{8}
}

func (x *ListSourcesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListSourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sources       []*Source              `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSourcesResponse) Reset() {
	*x = ListSourcesResponse{}
	mi := &file_domain_v1_model_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSourcesResponse) ProtoMessage() {}

func (x *ListSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_model_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSourcesResponse.ProtoReflect.Descriptor instead.
func (*ListSourcesResponse) Descriptor() ([]byte, []int) {
	return file_domain_v1_model_proto_rawDescGZIP(), []int{9}
}

func (x *ListSourcesResponse) GetSources() []*Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

var File_domain_v1_model_proto protoreflect.FileDescriptor

const file_domain_v1_model_proto_rawDesc = "" +
	"\n" +
	"\x15domain/v1/model.proto\x12\tdomain.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xeb\x01\n" +
	"\x06Source\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12'\n" +
	"\x03typ\x18\x03 \x01(\x0e2\x15.domain.v1.SourceTypeR\x03typ\x12@\n" +
	"\fupdateParams\x18\x04 \x01(\v2\x17.domain.v1.UpdateParamsH\x00R\fupdateParams\x88\x01\x01\x12%\n" +
	"\vcredentials\x18\x05 \x01(\fH\x01R\vcredentials\x88\x01\x01B\x0f\n" +
	"\r_updateParamsB\x0e\n" +
	"\f_credentials\"d\n" +
	"\fUpdateParams\x12 \n" +
	"\veveryPeriod\x18\x01 \x01(\x03R\veveryPeriod\x122\n" +
	"\x06onTime\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06onTime\"X\n" +
	"\x13CreateSourceRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12)\n" +
	"\x06source\x18\x02 \x01(\v2\x11.domain.v1.SourceR\x06source\"2\n" +
	"\x14CreateSourceResponse\x12\x1a\n" +
	"\bsourceId\x18\x01 \x01(\x03R\bsourceId\"F\n" +
	"\x10GetSourceRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bsourceId\x18\x02 \x01(\x03R\bsourceId\">\n" +
	"\x11GetSourceResponse\x12)\n" +
	"\x06source\x18\x01 \x01(\v2\x11.domain.v1.SourceR\x06source\"\xa3\x02\n" +
	"\x13UpdateSourceRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bsourceId\x18\x02 \x01(\x03R\bsourceId\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x1d\n" +
	"\acontent\x18\x04 \x01(\fH\x01R\acontent\x88\x01\x01\x12@\n" +
	"\fupdateParams\x18\x05 \x01(\v2\x17.domain.v1.UpdateParamsH\x02R\fupdateParams\x88\x01\x01\x12%\n" +
	"\vcredentials\x18\x06 \x01(\fH\x03R\vcredentials\x88\x01\x01B\b\n" +
	"\x06_titleB\n" +
	"\n" +
	"\b_contentB\x0f\n" +
	"\r_updateParamsB\x0e\n" +
	"\f_credentials\"I\n" +
	"\x13DeleteSourceRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\bsourceId\x18\x02 \x01(\x03R\bsourceId\",\n" +
	"\x12ListSourcesRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\"B\n" +
	"\x13ListSourcesResponse\x12+\n" +
	"\asources\x18\x01 \x03(\v2\x11.domain.v1.SourceR\asources*r\n" +
	"\n" +
	"SourceType\x12\x19\n" +
	"\x15UNDEFINED_SOURCE_TYPE\x10\x00\x12\x0e\n" +
	"\n" +
	"WEB_SOURCE\x10\x01\x12\x0f\n" +
	"\vSINGLE_FILE\x10\x02\x12\x12\n" +
	"\x0eARCHIVED_FILES\x10\x03\x12\x14\n" +
	"\x10WITH_CREDENTIALS\x10\x04B\x14Z\x12internal/domain/pbb\x06proto3"

var (
	file_domain_v1_model_proto_rawDescOnce sync.Once
	file_domain_v1_model_proto_rawDescData []byte
)

func file_domain_v1_model_proto_rawDescGZIP() []byte {
	file_domain_v1_model_proto_rawDescOnce.Do(func() {
		file_domain_v1_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_v1_model_proto_rawDesc), len(file_domain_v1_model_proto_rawDesc)))
	})
	return file_domain_v1_model_proto_rawDescData
}

var file_domain_v1_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_domain_v1_model_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_domain_v1_model_proto_goTypes = []any{
	(SourceType)(0),               // 0: domain.v1.SourceType
	(*Source)(nil),                // 1: domain.v1.Source
	(*UpdateParams)(nil),          // 2: domain.v1.UpdateParams
	(*CreateSourceRequest)(nil),   // 3: domain.v1.CreateSourceRequest
	(*CreateSourceResponse)(nil),  // 4: domain.v1.CreateSourceResponse
	(*GetSourceRequest)(nil),      // 5: domain.v1.GetSourceRequest
	(*GetSourceResponse)(nil),     // 6: domain.v1.GetSourceResponse
	(*UpdateSourceRequest)(nil),   // 7: domain.v1.UpdateSourceRequest
	(*DeleteSourceRequest)(nil),   // 8: domain.v1.DeleteSourceRequest
	(*ListSourcesRequest)(nil),    // 9: domain.v1.ListSourcesRequest
	(*ListSourcesResponse)(nil),   // 10: domain.v1.ListSourcesResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_domain_v1_model_proto_depIdxs = []int32{
	0,  // 0: domain.v1.Source.typ:type_name -> domain.v1.SourceType
	2,  // 1: domain.v1.Source.updateParams:type_name -> domain.v1.UpdateParams
	11, // 2: domain.v1.UpdateParams.onTime:type_name -> google.protobuf.Timestamp
	1,  // 3: domain.v1.CreateSourceRequest.source:type_name -> domain.v1.Source
	1,  // 4: domain.v1.GetSourceResponse.source:type_name -> domain.v1.Source
	2,  // 5: domain.v1.UpdateSourceRequest.updateParams:type_name -> domain.v1.UpdateParams
	1,  // 6: domain.v1.ListSourcesResponse.sources:type_name -> domain.v1.Source
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_domain_v1_model_proto_init() }
func file_domain_v1_model_proto_init() {
	if File_domain_v1_model_proto != nil {
		return
	}
	file_domain_v1_model_proto_msgTypes[0].OneofWrappers = []any{}
	file_domain_v1_model_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_v1_model_proto_rawDesc), len(file_domain_v1_model_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_v1_model_proto_goTypes,
		DependencyIndexes: file_domain_v1_model_proto_depIdxs,
		EnumInfos:         file_domain_v1_model_proto_enumTypes,
		MessageInfos:      file_domain_v1_model_proto_msgTypes,
	}.Build()
	File_domain_v1_model_proto = out.File
	file_domain_v1_model_proto_goTypes = nil
	file_domain_v1_model_proto_depIdxs = nil
}
