// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/v1/scenario_model.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateScenarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MultiQuery    *MultiQuery            `protobuf:"bytes,1,opt,name=multiQuery,proto3,oneof" json:"multiQuery,omitempty"`
	Reranker      *Reranker              `protobuf:"bytes,2,opt,name=reranker,proto3,oneof" json:"reranker,omitempty"`
	VectorSearch  *VectorSearch          `protobuf:"bytes,3,opt,name=vectorSearch,proto3,oneof" json:"vectorSearch,omitempty"`
	Model         *LlmModel              `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScenarioRequest) Reset() {
	*x = CreateScenarioRequest{}
	mi := &file_domain_v1_scenario_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScenarioRequest) ProtoMessage() {}

func (x *CreateScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_scenario_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScenarioRequest.ProtoReflect.Descriptor instead.
func (*CreateScenarioRequest) Descriptor() ([]byte, []int) {
	return file_domain_v1_scenario_model_proto_rawDescGZIP(), []int{0}
}

func (x *CreateScenarioRequest) GetMultiQuery() *MultiQuery {
	if x != nil {
		return x.MultiQuery
	}
	return nil
}

func (x *CreateScenarioRequest) GetReranker() *Reranker {
	if x != nil {
		return x.Reranker
	}
	return nil
}

func (x *CreateScenarioRequest) GetVectorSearch() *VectorSearch {
	if x != nil {
		return x.VectorSearch
	}
	return nil
}

func (x *CreateScenarioRequest) GetModel() *LlmModel {
	if x != nil {
		return x.Model
	}
	return nil
}

type GetScenarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId    int64                  `protobuf:"varint,1,opt,name=scenarioId,proto3" json:"scenarioId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScenarioRequest) Reset() {
	*x = GetScenarioRequest{}
	mi := &file_domain_v1_scenario_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScenarioRequest) ProtoMessage() {}

func (x *GetScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_scenario_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScenarioRequest.ProtoReflect.Descriptor instead.
func (*GetScenarioRequest) Descriptor() ([]byte, []int) {
	return file_domain_v1_scenario_model_proto_rawDescGZIP(), []int{1}
}

func (x *GetScenarioRequest) GetScenarioId() int64 {
	if x != nil {
		return x.ScenarioId
	}
	return 0
}

type GetScenarioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenario      *Scenario              `protobuf:"bytes,1,opt,name=scenario,proto3" json:"scenario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetScenarioResponse) Reset() {
	*x = GetScenarioResponse{}
	mi := &file_domain_v1_scenario_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetScenarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetScenarioResponse) ProtoMessage() {}

func (x *GetScenarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_scenario_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetScenarioResponse.ProtoReflect.Descriptor instead.
func (*GetScenarioResponse) Descriptor() ([]byte, []int) {
	return file_domain_v1_scenario_model_proto_rawDescGZIP(), []int{2}
}

func (x *GetScenarioResponse) GetScenario() *Scenario {
	if x != nil {
		return x.Scenario
	}
	return nil
}

type UpdateScenarioRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId        int64                  `protobuf:"varint,1,opt,name=scenarioId,proto3" json:"scenarioId,omitempty"`
	UseMultiquery     *bool                  `protobuf:"varint,2,opt,name=useMultiquery,proto3,oneof" json:"useMultiquery,omitempty"`
	NQueries          *int64                 `protobuf:"varint,3,opt,name=nQueries,proto3,oneof" json:"nQueries,omitempty"`            // Количество перефразированных вопросов
	QueryModelName    *string                `protobuf:"bytes,4,opt,name=queryModelName,proto3,oneof" json:"queryModelName,omitempty"` // Пока не знаю нучно ли будет
	UseRerank         *bool                  `protobuf:"varint,5,opt,name=useRerank,proto3,oneof" json:"useRerank,omitempty"`
	RerankerModel     *string                `protobuf:"bytes,6,opt,name=rerankerModel,proto3,oneof" json:"rerankerModel,omitempty"`
	RerankerMaxLength *int64                 `protobuf:"varint,7,opt,name=rerankerMaxLength,proto3,oneof" json:"rerankerMaxLength,omitempty"`
	RerankerTopK      *int64                 `protobuf:"varint,8,opt,name=rerankerTopK,proto3,oneof" json:"rerankerTopK,omitempty"` // Количество чанков после реранкинга
	ModelName         *string                `protobuf:"bytes,9,opt,name=modelName,proto3,oneof" json:"modelName,omitempty"`
	Temperature       *float32               `protobuf:"fixed32,10,opt,name=temperature,proto3,oneof" json:"temperature,omitempty"`
	ModelTopK         *int64                 `protobuf:"varint,11,opt,name=modelTopK,proto3,oneof" json:"modelTopK,omitempty"`
	TopP              *float32               `protobuf:"fixed32,12,opt,name=topP,proto3,oneof" json:"topP,omitempty"`
	SystemPrompt      *string                `protobuf:"bytes,13,opt,name=systemPrompt,proto3,oneof" json:"systemPrompt,omitempty"`
	TopN              *int64                 `protobuf:"varint,14,opt,name=topN,proto3,oneof" json:"topN,omitempty"` // Сколько чанков забирать при векторном поиске.
	Threshold         *float32               `protobuf:"fixed32,15,opt,name=threshold,proto3,oneof" json:"threshold,omitempty"`
	SearchByQuery     *bool                  `protobuf:"varint,16,opt,name=searchByQuery,proto3,oneof" json:"searchByQuery,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateScenarioRequest) Reset() {
	*x = UpdateScenarioRequest{}
	mi := &file_domain_v1_scenario_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScenarioRequest) ProtoMessage() {}

func (x *UpdateScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_scenario_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScenarioRequest.ProtoReflect.Descriptor instead.
func (*UpdateScenarioRequest) Descriptor() ([]byte, []int) {
	return file_domain_v1_scenario_model_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateScenarioRequest) GetScenarioId() int64 {
	if x != nil {
		return x.ScenarioId
	}
	return 0
}

func (x *UpdateScenarioRequest) GetUseMultiquery() bool {
	if x != nil && x.UseMultiquery != nil {
		return *x.UseMultiquery
	}
	return false
}

func (x *UpdateScenarioRequest) GetNQueries() int64 {
	if x != nil && x.NQueries != nil {
		return *x.NQueries
	}
	return 0
}

func (x *UpdateScenarioRequest) GetQueryModelName() string {
	if x != nil && x.QueryModelName != nil {
		return *x.QueryModelName
	}
	return ""
}

func (x *UpdateScenarioRequest) GetUseRerank() bool {
	if x != nil && x.UseRerank != nil {
		return *x.UseRerank
	}
	return false
}

func (x *UpdateScenarioRequest) GetRerankerModel() string {
	if x != nil && x.RerankerModel != nil {
		return *x.RerankerModel
	}
	return ""
}

func (x *UpdateScenarioRequest) GetRerankerMaxLength() int64 {
	if x != nil && x.RerankerMaxLength != nil {
		return *x.RerankerMaxLength
	}
	return 0
}

func (x *UpdateScenarioRequest) GetRerankerTopK() int64 {
	if x != nil && x.RerankerTopK != nil {
		return *x.RerankerTopK
	}
	return 0
}

func (x *UpdateScenarioRequest) GetModelName() string {
	if x != nil && x.ModelName != nil {
		return *x.ModelName
	}
	return ""
}

func (x *UpdateScenarioRequest) GetTemperature() float32 {
	if x != nil && x.Temperature != nil {
		return *x.Temperature
	}
	return 0
}

func (x *UpdateScenarioRequest) GetModelTopK() int64 {
	if x != nil && x.ModelTopK != nil {
		return *x.ModelTopK
	}
	return 0
}

func (x *UpdateScenarioRequest) GetTopP() float32 {
	if x != nil && x.TopP != nil {
		return *x.TopP
	}
	return 0
}

func (x *UpdateScenarioRequest) GetSystemPrompt() string {
	if x != nil && x.SystemPrompt != nil {
		return *x.SystemPrompt
	}
	return ""
}

func (x *UpdateScenarioRequest) GetTopN() int64 {
	if x != nil && x.TopN != nil {
		return *x.TopN
	}
	return 0
}

func (x *UpdateScenarioRequest) GetThreshold() float32 {
	if x != nil && x.Threshold != nil {
		return *x.Threshold
	}
	return 0
}

func (x *UpdateScenarioRequest) GetSearchByQuery() bool {
	if x != nil && x.SearchByQuery != nil {
		return *x.SearchByQuery
	}
	return false
}

type DeleteScenarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScenarioId    int64                  `protobuf:"varint,1,opt,name=scenarioId,proto3" json:"scenarioId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScenarioRequest) Reset() {
	*x = DeleteScenarioRequest{}
	mi := &file_domain_v1_scenario_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScenarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScenarioRequest) ProtoMessage() {}

func (x *DeleteScenarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_scenario_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScenarioRequest.ProtoReflect.Descriptor instead.
func (*DeleteScenarioRequest) Descriptor() ([]byte, []int) {
	return file_domain_v1_scenario_model_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteScenarioRequest) GetScenarioId() int64 {
	if x != nil {
		return x.ScenarioId
	}
	return 0
}

type ListScenariosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScenariosRequest) Reset() {
	*x = ListScenariosRequest{}
	mi := &file_domain_v1_scenario_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScenariosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScenariosRequest) ProtoMessage() {}

func (x *ListScenariosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_scenario_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScenariosRequest.ProtoReflect.Descriptor instead.
func (*ListScenariosRequest) Descriptor() ([]byte, []int) {
	return file_domain_v1_scenario_model_proto_rawDescGZIP(), []int{5}
}

func (x *ListScenariosRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListScenariosRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListScenariosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scenarios     []*Scenario            `protobuf:"bytes,1,rep,name=scenarios,proto3" json:"scenarios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScenariosResponse) Reset() {
	*x = ListScenariosResponse{}
	mi := &file_domain_v1_scenario_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScenariosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScenariosResponse) ProtoMessage() {}

func (x *ListScenariosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domain_v1_scenario_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScenariosResponse.ProtoReflect.Descriptor instead.
func (*ListScenariosResponse) Descriptor() ([]byte, []int) {
	return file_domain_v1_scenario_model_proto_rawDescGZIP(), []int{6}
}

func (x *ListScenariosResponse) GetScenarios() []*Scenario {
	if x != nil {
		return x.Scenarios
	}
	return nil
}

var File_domain_v1_scenario_model_proto protoreflect.FileDescriptor

const file_domain_v1_scenario_model_proto_rawDesc = "" +
	"\n" +
	"\x1edomain/v1/scenario_model.proto\x12\tdomain.v1\x1a\x11ml/v1/model.proto\"\x93\x02\n" +
	"\x15CreateScenarioRequest\x126\n" +
	"\n" +
	"multiQuery\x18\x01 \x01(\v2\x11.pb.ml.MultiQueryH\x00R\n" +
	"multiQuery\x88\x01\x01\x120\n" +
	"\breranker\x18\x02 \x01(\v2\x0f.pb.ml.RerankerH\x01R\breranker\x88\x01\x01\x12<\n" +
	"\fvectorSearch\x18\x03 \x01(\v2\x13.pb.ml.VectorSearchH\x02R\fvectorSearch\x88\x01\x01\x12%\n" +
	"\x05model\x18\x04 \x01(\v2\x0f.pb.ml.LlmModelR\x05modelB\r\n" +
	"\v_multiQueryB\v\n" +
	"\t_rerankerB\x0f\n" +
	"\r_vectorSearch\"4\n" +
	"\x12GetScenarioRequest\x12\x1e\n" +
	"\n" +
	"scenarioId\x18\x01 \x01(\x03R\n" +
	"scenarioId\"B\n" +
	"\x13GetScenarioResponse\x12+\n" +
	"\bscenario\x18\x01 \x01(\v2\x0f.pb.ml.ScenarioR\bscenario\"\xd8\x06\n" +
	"\x15UpdateScenarioRequest\x12\x1e\n" +
	"\n" +
	"scenarioId\x18\x01 \x01(\x03R\n" +
	"scenarioId\x12)\n" +
	"\ruseMultiquery\x18\x02 \x01(\bH\x00R\ruseMultiquery\x88\x01\x01\x12\x1f\n" +
	"\bnQueries\x18\x03 \x01(\x03H\x01R\bnQueries\x88\x01\x01\x12+\n" +
	"\x0equeryModelName\x18\x04 \x01(\tH\x02R\x0equeryModelName\x88\x01\x01\x12!\n" +
	"\tuseRerank\x18\x05 \x01(\bH\x03R\tuseRerank\x88\x01\x01\x12)\n" +
	"\rrerankerModel\x18\x06 \x01(\tH\x04R\rrerankerModel\x88\x01\x01\x121\n" +
	"\x11rerankerMaxLength\x18\a \x01(\x03H\x05R\x11rerankerMaxLength\x88\x01\x01\x12'\n" +
	"\frerankerTopK\x18\b \x01(\x03H\x06R\frerankerTopK\x88\x01\x01\x12!\n" +
	"\tmodelName\x18\t \x01(\tH\aR\tmodelName\x88\x01\x01\x12%\n" +
	"\vtemperature\x18\n" +
	" \x01(\x02H\bR\vtemperature\x88\x01\x01\x12!\n" +
	"\tmodelTopK\x18\v \x01(\x03H\tR\tmodelTopK\x88\x01\x01\x12\x17\n" +
	"\x04topP\x18\f \x01(\x02H\n" +
	"R\x04topP\x88\x01\x01\x12'\n" +
	"\fsystemPrompt\x18\r \x01(\tH\vR\fsystemPrompt\x88\x01\x01\x12\x17\n" +
	"\x04topN\x18\x0e \x01(\x03H\fR\x04topN\x88\x01\x01\x12!\n" +
	"\tthreshold\x18\x0f \x01(\x02H\rR\tthreshold\x88\x01\x01\x12)\n" +
	"\rsearchByQuery\x18\x10 \x01(\bH\x0eR\rsearchByQuery\x88\x01\x01B\x10\n" +
	"\x0e_useMultiqueryB\v\n" +
	"\t_nQueriesB\x11\n" +
	"\x0f_queryModelNameB\f\n" +
	"\n" +
	"_useRerankB\x10\n" +
	"\x0e_rerankerModelB\x14\n" +
	"\x12_rerankerMaxLengthB\x0f\n" +
	"\r_rerankerTopKB\f\n" +
	"\n" +
	"_modelNameB\x0e\n" +
	"\f_temperatureB\f\n" +
	"\n" +
	"_modelTopKB\a\n" +
	"\x05_topPB\x0f\n" +
	"\r_systemPromptB\a\n" +
	"\x05_topNB\f\n" +
	"\n" +
	"_thresholdB\x10\n" +
	"\x0e_searchByQuery\"7\n" +
	"\x15DeleteScenarioRequest\x12\x1e\n" +
	"\n" +
	"scenarioId\x18\x01 \x01(\x03R\n" +
	"scenarioId\"D\n" +
	"\x14ListScenariosRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\"F\n" +
	"\x15ListScenariosResponse\x12-\n" +
	"\tscenarios\x18\x01 \x03(\v2\x0f.pb.ml.ScenarioR\tscenariosB\x14Z\x12internal/domain/pbb\x06proto3"

var (
	file_domain_v1_scenario_model_proto_rawDescOnce sync.Once
	file_domain_v1_scenario_model_proto_rawDescData []byte
)

func file_domain_v1_scenario_model_proto_rawDescGZIP() []byte {
	file_domain_v1_scenario_model_proto_rawDescOnce.Do(func() {
		file_domain_v1_scenario_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domain_v1_scenario_model_proto_rawDesc), len(file_domain_v1_scenario_model_proto_rawDesc)))
	})
	return file_domain_v1_scenario_model_proto_rawDescData
}

var file_domain_v1_scenario_model_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_domain_v1_scenario_model_proto_goTypes = []any{
	(*CreateScenarioRequest)(nil), // 0: domain.v1.CreateScenarioRequest
	(*GetScenarioRequest)(nil),    // 1: domain.v1.GetScenarioRequest
	(*GetScenarioResponse)(nil),   // 2: domain.v1.GetScenarioResponse
	(*UpdateScenarioRequest)(nil), // 3: domain.v1.UpdateScenarioRequest
	(*DeleteScenarioRequest)(nil), // 4: domain.v1.DeleteScenarioRequest
	(*ListScenariosRequest)(nil),  // 5: domain.v1.ListScenariosRequest
	(*ListScenariosResponse)(nil), // 6: domain.v1.ListScenariosResponse
	(*MultiQuery)(nil),            // 7: pb.ml.MultiQuery
	(*Reranker)(nil),              // 8: pb.ml.Reranker
	(*VectorSearch)(nil),          // 9: pb.ml.VectorSearch
	(*LlmModel)(nil),              // 10: pb.ml.LlmModel
	(*Scenario)(nil),              // 11: pb.ml.Scenario
}
var file_domain_v1_scenario_model_proto_depIdxs = []int32{
	7,  // 0: domain.v1.CreateScenarioRequest.multiQuery:type_name -> pb.ml.MultiQuery
	8,  // 1: domain.v1.CreateScenarioRequest.reranker:type_name -> pb.ml.Reranker
	9,  // 2: domain.v1.CreateScenarioRequest.vectorSearch:type_name -> pb.ml.VectorSearch
	10, // 3: domain.v1.CreateScenarioRequest.model:type_name -> pb.ml.LlmModel
	11, // 4: domain.v1.GetScenarioResponse.scenario:type_name -> pb.ml.Scenario
	11, // 5: domain.v1.ListScenariosResponse.scenarios:type_name -> pb.ml.Scenario
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_domain_v1_scenario_model_proto_init() }
func file_domain_v1_scenario_model_proto_init() {
	if File_domain_v1_scenario_model_proto != nil {
		return
	}
	file_ml_v1_model_proto_init()
	file_domain_v1_scenario_model_proto_msgTypes[0].OneofWrappers = []any{}
	file_domain_v1_scenario_model_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_v1_scenario_model_proto_rawDesc), len(file_domain_v1_scenario_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domain_v1_scenario_model_proto_goTypes,
		DependencyIndexes: file_domain_v1_scenario_model_proto_depIdxs,
		MessageInfos:      file_domain_v1_scenario_model_proto_msgTypes,
	}.Build()
	File_domain_v1_scenario_model_proto = out.File
	file_domain_v1_scenario_model_proto_goTypes = nil
	file_domain_v1_scenario_model_proto_depIdxs = nil
}
