// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: domain/v1/user_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_domain_v1_user_service_proto protoreflect.FileDescriptor

const file_domain_v1_user_service_proto_rawDesc = "" +
	"\n" +
	"\x1cdomain/v1/user_service.proto\x12\tdomain.v1\x1a\x1adomain/v1/user_model.proto\x1a\x1bgoogle/protobuf/empty.proto2\x95\x02\n" +
	"\vUserService\x12=\n" +
	"\n" +
	"CreateUser\x12\x1c.domain.v1.CreateUserRequest\x1a\x0f.domain.v1.User\"\x00\x127\n" +
	"\aGetUser\x12\x19.domain.v1.GetUserRequest\x1a\x0f.domain.v1.User\"\x00\x12D\n" +
	"\n" +
	"DeleteUser\x12\x1c.domain.v1.DeleteUserRequest\x1a\x16.google.protobuf.Empty\"\x00\x12H\n" +
	"\tListUsers\x12\x1b.domain.v1.ListUsersRequest\x1a\x1c.domain.v1.ListUsersResponse\"\x00B\x14Z\x12internal/domain/pbb\x06proto3"

var file_domain_v1_user_service_proto_goTypes = []any{
	(*CreateUserRequest)(nil), // 0: domain.v1.CreateUserRequest
	(*GetUserRequest)(nil),    // 1: domain.v1.GetUserRequest
	(*DeleteUserRequest)(nil), // 2: domain.v1.DeleteUserRequest
	(*ListUsersRequest)(nil),  // 3: domain.v1.ListUsersRequest
	(*User)(nil),              // 4: domain.v1.User
	(*emptypb.Empty)(nil),     // 5: google.protobuf.Empty
	(*ListUsersResponse)(nil), // 6: domain.v1.ListUsersResponse
}
var file_domain_v1_user_service_proto_depIdxs = []int32{
	0, // 0: domain.v1.UserService.CreateUser:input_type -> domain.v1.CreateUserRequest
	1, // 1: domain.v1.UserService.GetUser:input_type -> domain.v1.GetUserRequest
	2, // 2: domain.v1.UserService.DeleteUser:input_type -> domain.v1.DeleteUserRequest
	3, // 3: domain.v1.UserService.ListUsers:input_type -> domain.v1.ListUsersRequest
	4, // 4: domain.v1.UserService.CreateUser:output_type -> domain.v1.User
	4, // 5: domain.v1.UserService.GetUser:output_type -> domain.v1.User
	5, // 6: domain.v1.UserService.DeleteUser:output_type -> google.protobuf.Empty
	6, // 7: domain.v1.UserService.ListUsers:output_type -> domain.v1.ListUsersResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_domain_v1_user_service_proto_init() }
func file_domain_v1_user_service_proto_init() {
	if File_domain_v1_user_service_proto != nil {
		return
	}
	file_domain_v1_user_model_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domain_v1_user_service_proto_rawDesc), len(file_domain_v1_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_domain_v1_user_service_proto_goTypes,
		DependencyIndexes: file_domain_v1_user_service_proto_depIdxs,
	}.Build()
	File_domain_v1_user_service_proto = out.File
	file_domain_v1_user_service_proto_goTypes = nil
	file_domain_v1_user_service_proto_depIdxs = nil
}
