// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: chat/v1/model.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseStatus int32

const (
	ResponseStatus_RESPONSE_UNDEFINED  ResponseStatus = 0
	ResponseStatus_RESPONSE_CREATED    ResponseStatus = 1
	ResponseStatus_RESPONSE_PROCESSING ResponseStatus = 2
	ResponseStatus_RESPONSE_SUCCESS    ResponseStatus = 3
	ResponseStatus_RESPONSE_ERROR      ResponseStatus = 4
	ResponseStatus_RESPONSE_CANCELED   ResponseStatus = 5
)

// Enum value maps for ResponseStatus.
var (
	ResponseStatus_name = map[int32]string{
		0: "RESPONSE_UNDEFINED",
		1: "RESPONSE_CREATED",
		2: "RESPONSE_PROCESSING",
		3: "RESPONSE_SUCCESS",
		4: "RESPONSE_ERROR",
		5: "RESPONSE_CANCELED",
	}
	ResponseStatus_value = map[string]int32{
		"RESPONSE_UNDEFINED":  0,
		"RESPONSE_CREATED":    1,
		"RESPONSE_PROCESSING": 2,
		"RESPONSE_SUCCESS":    3,
		"RESPONSE_ERROR":      4,
		"RESPONSE_CANCELED":   5,
	}
)

func (x ResponseStatus) Enum() *ResponseStatus {
	p := new(ResponseStatus)
	*p = x
	return p
}

func (x ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_chat_v1_model_proto_enumTypes[0].Descriptor()
}

func (ResponseStatus) Type() protoreflect.EnumType {
	return &file_chat_v1_model_proto_enumTypes[0]
}

func (x ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseStatus.Descriptor instead.
func (ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_chat_v1_model_proto_rawDescGZIP(), []int{0}
}

type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	ChatId        string                 `protobuf:"bytes,3,opt,name=chatId,proto3" json:"chatId,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	DomainId      *int64                 `protobuf:"varint,5,opt,name=domainId,proto3,oneof" json:"domainId,omitempty"`
	SourceIds     []string               `protobuf:"bytes,6,rep,name=sourceIds,proto3" json:"sourceIds,omitempty"`
	ScenarioId    *int64                 `protobuf:"varint,7,opt,name=scenarioId,proto3,oneof" json:"scenarioId,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,8,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_chat_v1_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_chat_v1_model_proto_rawDescGZIP(), []int{0}
}

func (x *Query) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Query) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Query) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Query) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Query) GetDomainId() int64 {
	if x != nil && x.DomainId != nil {
		return *x.DomainId
	}
	return 0
}

func (x *Query) GetSourceIds() []string {
	if x != nil {
		return x.SourceIds
	}
	return nil
}

func (x *Query) GetScenarioId() int64 {
	if x != nil && x.ScenarioId != nil {
		return *x.ScenarioId
	}
	return 0
}

func (x *Query) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Query) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	QueryId       int64                  `protobuf:"varint,2,opt,name=queryId,proto3" json:"queryId,omitempty"`
	ChatId        string                 `protobuf:"bytes,3,opt,name=chatId,proto3" json:"chatId,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Status        ResponseStatus         `protobuf:"varint,5,opt,name=status,proto3,enum=chat.v1.ResponseStatus" json:"status,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,6,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_chat_v1_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_chat_v1_model_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Response) GetQueryId() int64 {
	if x != nil {
		return x.QueryId
	}
	return 0
}

func (x *Response) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *Response) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Response) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_RESPONSE_UNDEFINED
}

func (x *Response) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Response) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Response) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Content struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *Query                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Response      *Response              `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_chat_v1_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_chat_v1_model_proto_rawDescGZIP(), []int{2}
}

func (x *Content) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *Content) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

type Chat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       []*Content             `protobuf:"bytes,4,rep,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_chat_v1_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_chat_v1_model_proto_rawDescGZIP(), []int{3}
}

func (x *Chat) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chat) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Chat) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Chat) GetContent() []*Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Chat) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Chat) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ChunkedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       int64                  `protobuf:"varint,1,opt,name=queryId,proto3" json:"queryId,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	SourceIds     []string               `protobuf:"bytes,3,rep,name=sourceIds,proto3" json:"sourceIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChunkedResponse) Reset() {
	*x = ChunkedResponse{}
	mi := &file_chat_v1_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChunkedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChunkedResponse) ProtoMessage() {}

func (x *ChunkedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChunkedResponse.ProtoReflect.Descriptor instead.
func (*ChunkedResponse) Descriptor() ([]byte, []int) {
	return file_chat_v1_model_proto_rawDescGZIP(), []int{4}
}

func (x *ChunkedResponse) GetQueryId() int64 {
	if x != nil {
		return x.QueryId
	}
	return 0
}

func (x *ChunkedResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChunkedResponse) GetSourceIds() []string {
	if x != nil {
		return x.SourceIds
	}
	return nil
}

type GetChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chatId,proto3" json:"chatId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatRequest) Reset() {
	*x = GetChatRequest{}
	mi := &file_chat_v1_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatRequest) ProtoMessage() {}

func (x *GetChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatRequest.ProtoReflect.Descriptor instead.
func (*GetChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_model_proto_rawDescGZIP(), []int{5}
}

func (x *GetChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type RenameChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chatId,proto3" json:"chatId,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameChatRequest) Reset() {
	*x = RenameChatRequest{}
	mi := &file_chat_v1_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameChatRequest) ProtoMessage() {}

func (x *RenameChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameChatRequest.ProtoReflect.Descriptor instead.
func (*RenameChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_model_proto_rawDescGZIP(), []int{6}
}

func (x *RenameChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *RenameChatRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type DeleteChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chatId,proto3" json:"chatId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatRequest) Reset() {
	*x = DeleteChatRequest{}
	mi := &file_chat_v1_model_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatRequest) ProtoMessage() {}

func (x *DeleteChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_model_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatRequest.ProtoReflect.Descriptor instead.
func (*DeleteChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_model_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type CleanupChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        string                 `protobuf:"bytes,1,opt,name=chatId,proto3" json:"chatId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupChatRequest) Reset() {
	*x = CleanupChatRequest{}
	mi := &file_chat_v1_model_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupChatRequest) ProtoMessage() {}

func (x *CleanupChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_model_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupChatRequest.ProtoReflect.Descriptor instead.
func (*CleanupChatRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_model_proto_rawDescGZIP(), []int{8}
}

func (x *CleanupChatRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

type ListChatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatsRequest) Reset() {
	*x = ListChatsRequest{}
	mi := &file_chat_v1_model_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatsRequest) ProtoMessage() {}

func (x *ListChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_model_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatsRequest.ProtoReflect.Descriptor instead.
func (*ListChatsRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_model_proto_rawDescGZIP(), []int{9}
}

func (x *ListChatsRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListChatsRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*Chat                `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChatsResponse) Reset() {
	*x = ListChatsResponse{}
	mi := &file_chat_v1_model_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChatsResponse) ProtoMessage() {}

func (x *ListChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_model_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChatsResponse.ProtoReflect.Descriptor instead.
func (*ListChatsResponse) Descriptor() ([]byte, []int) {
	return file_chat_v1_model_proto_rawDescGZIP(), []int{10}
}

func (x *ListChatsResponse) GetChats() []*Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

type ProcessQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ChatId        string                 `protobuf:"bytes,2,opt,name=chatId,proto3" json:"chatId,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	DomainId      *int64                 `protobuf:"varint,4,opt,name=domainId,proto3,oneof" json:"domainId,omitempty"`
	SourceIds     []string               `protobuf:"bytes,5,rep,name=sourceIds,proto3" json:"sourceIds,omitempty"`
	ScenarioId    *int64                 `protobuf:"varint,6,opt,name=scenarioId,proto3,oneof" json:"scenarioId,omitempty"`
	Metadata      []byte                 `protobuf:"bytes,7,opt,name=metadata,proto3,oneof" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessQueryRequest) Reset() {
	*x = ProcessQueryRequest{}
	mi := &file_chat_v1_model_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessQueryRequest) ProtoMessage() {}

func (x *ProcessQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_model_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessQueryRequest.ProtoReflect.Descriptor instead.
func (*ProcessQueryRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_model_proto_rawDescGZIP(), []int{11}
}

func (x *ProcessQueryRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ProcessQueryRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ProcessQueryRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ProcessQueryRequest) GetDomainId() int64 {
	if x != nil && x.DomainId != nil {
		return *x.DomainId
	}
	return 0
}

func (x *ProcessQueryRequest) GetSourceIds() []string {
	if x != nil {
		return x.SourceIds
	}
	return nil
}

func (x *ProcessQueryRequest) GetScenarioId() int64 {
	if x != nil && x.ScenarioId != nil {
		return *x.ScenarioId
	}
	return 0
}

func (x *ProcessQueryRequest) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CancelProcessingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       int64                  `protobuf:"varint,1,opt,name=queryId,proto3" json:"queryId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelProcessingRequest) Reset() {
	*x = CancelProcessingRequest{}
	mi := &file_chat_v1_model_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelProcessingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelProcessingRequest) ProtoMessage() {}

func (x *CancelProcessingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chat_v1_model_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelProcessingRequest.ProtoReflect.Descriptor instead.
func (*CancelProcessingRequest) Descriptor() ([]byte, []int) {
	return file_chat_v1_model_proto_rawDescGZIP(), []int{12}
}

func (x *CancelProcessingRequest) GetQueryId() int64 {
	if x != nil {
		return x.QueryId
	}
	return 0
}

var File_chat_v1_model_proto protoreflect.FileDescriptor

const file_chat_v1_model_proto_rawDesc = "" +
	"\n" +
	"\x13chat/v1/model.proto\x12\achat.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc9\x02\n" +
	"\x05Query\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06chatId\x18\x03 \x01(\tR\x06chatId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x1f\n" +
	"\bdomainId\x18\x05 \x01(\x03H\x00R\bdomainId\x88\x01\x01\x12\x1c\n" +
	"\tsourceIds\x18\x06 \x03(\tR\tsourceIds\x12#\n" +
	"\n" +
	"scenarioId\x18\a \x01(\x03H\x01R\n" +
	"scenarioId\x88\x01\x01\x12\x1f\n" +
	"\bmetadata\x18\b \x01(\fH\x02R\bmetadata\x88\x01\x01\x128\n" +
	"\tcreatedAt\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\v\n" +
	"\t_domainIdB\r\n" +
	"\v_scenarioIdB\v\n" +
	"\t_metadata\"\xb9\x02\n" +
	"\bResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aqueryId\x18\x02 \x01(\x03R\aqueryId\x12\x16\n" +
	"\x06chatId\x18\x03 \x01(\tR\x06chatId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12/\n" +
	"\x06status\x18\x05 \x01(\x0e2\x17.chat.v1.ResponseStatusR\x06status\x12\x1f\n" +
	"\bmetadata\x18\x06 \x01(\fH\x00R\bmetadata\x88\x01\x01\x128\n" +
	"\tcreatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\v\n" +
	"\t_metadata\"^\n" +
	"\aContent\x12$\n" +
	"\x05query\x18\x01 \x01(\v2\x0e.chat.v1.QueryR\x05query\x12-\n" +
	"\bresponse\x18\x02 \x01(\v2\x11.chat.v1.ResponseR\bresponse\"\xe4\x01\n" +
	"\x04Chat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12*\n" +
	"\acontent\x18\x04 \x03(\v2\x10.chat.v1.ContentR\acontent\x128\n" +
	"\tcreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x128\n" +
	"\tupdatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"c\n" +
	"\x0fChunkedResponse\x12\x18\n" +
	"\aqueryId\x18\x01 \x01(\x03R\aqueryId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1c\n" +
	"\tsourceIds\x18\x03 \x03(\tR\tsourceIds\"(\n" +
	"\x0eGetChatRequest\x12\x16\n" +
	"\x06chatId\x18\x01 \x01(\tR\x06chatId\"A\n" +
	"\x11RenameChatRequest\x12\x16\n" +
	"\x06chatId\x18\x01 \x01(\tR\x06chatId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"+\n" +
	"\x11DeleteChatRequest\x12\x16\n" +
	"\x06chatId\x18\x01 \x01(\tR\x06chatId\",\n" +
	"\x12CleanupChatRequest\x12\x16\n" +
	"\x06chatId\x18\x01 \x01(\tR\x06chatId\"@\n" +
	"\x10ListChatsRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\"8\n" +
	"\x11ListChatsResponse\x12#\n" +
	"\x05chats\x18\x01 \x03(\v2\r.chat.v1.ChatR\x05chats\"\x8d\x02\n" +
	"\x13ProcessQueryRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06chatId\x18\x02 \x01(\tR\x06chatId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1f\n" +
	"\bdomainId\x18\x04 \x01(\x03H\x00R\bdomainId\x88\x01\x01\x12\x1c\n" +
	"\tsourceIds\x18\x05 \x03(\tR\tsourceIds\x12#\n" +
	"\n" +
	"scenarioId\x18\x06 \x01(\x03H\x01R\n" +
	"scenarioId\x88\x01\x01\x12\x1f\n" +
	"\bmetadata\x18\a \x01(\fH\x02R\bmetadata\x88\x01\x01B\v\n" +
	"\t_domainIdB\r\n" +
	"\v_scenarioIdB\v\n" +
	"\t_metadata\"3\n" +
	"\x17CancelProcessingRequest\x12\x18\n" +
	"\aqueryId\x18\x01 \x01(\x03R\aqueryId*\x98\x01\n" +
	"\x0eResponseStatus\x12\x16\n" +
	"\x12RESPONSE_UNDEFINED\x10\x00\x12\x14\n" +
	"\x10RESPONSE_CREATED\x10\x01\x12\x17\n" +
	"\x13RESPONSE_PROCESSING\x10\x02\x12\x14\n" +
	"\x10RESPONSE_SUCCESS\x10\x03\x12\x12\n" +
	"\x0eRESPONSE_ERROR\x10\x04\x12\x15\n" +
	"\x11RESPONSE_CANCELED\x10\x05B\x12Z\x10internal/chat/pbb\x06proto3"

var (
	file_chat_v1_model_proto_rawDescOnce sync.Once
	file_chat_v1_model_proto_rawDescData []byte
)

func file_chat_v1_model_proto_rawDescGZIP() []byte {
	file_chat_v1_model_proto_rawDescOnce.Do(func() {
		file_chat_v1_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_v1_model_proto_rawDesc), len(file_chat_v1_model_proto_rawDesc)))
	})
	return file_chat_v1_model_proto_rawDescData
}

var file_chat_v1_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chat_v1_model_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_chat_v1_model_proto_goTypes = []any{
	(ResponseStatus)(0),             // 0: chat.v1.ResponseStatus
	(*Query)(nil),                   // 1: chat.v1.Query
	(*Response)(nil),                // 2: chat.v1.Response
	(*Content)(nil),                 // 3: chat.v1.Content
	(*Chat)(nil),                    // 4: chat.v1.Chat
	(*ChunkedResponse)(nil),         // 5: chat.v1.ChunkedResponse
	(*GetChatRequest)(nil),          // 6: chat.v1.GetChatRequest
	(*RenameChatRequest)(nil),       // 7: chat.v1.RenameChatRequest
	(*DeleteChatRequest)(nil),       // 8: chat.v1.DeleteChatRequest
	(*CleanupChatRequest)(nil),      // 9: chat.v1.CleanupChatRequest
	(*ListChatsRequest)(nil),        // 10: chat.v1.ListChatsRequest
	(*ListChatsResponse)(nil),       // 11: chat.v1.ListChatsResponse
	(*ProcessQueryRequest)(nil),     // 12: chat.v1.ProcessQueryRequest
	(*CancelProcessingRequest)(nil), // 13: chat.v1.CancelProcessingRequest
	(*timestamppb.Timestamp)(nil),   // 14: google.protobuf.Timestamp
}
var file_chat_v1_model_proto_depIdxs = []int32{
	14, // 0: chat.v1.Query.createdAt:type_name -> google.protobuf.Timestamp
	0,  // 1: chat.v1.Response.status:type_name -> chat.v1.ResponseStatus
	14, // 2: chat.v1.Response.createdAt:type_name -> google.protobuf.Timestamp
	14, // 3: chat.v1.Response.updatedAt:type_name -> google.protobuf.Timestamp
	1,  // 4: chat.v1.Content.query:type_name -> chat.v1.Query
	2,  // 5: chat.v1.Content.response:type_name -> chat.v1.Response
	3,  // 6: chat.v1.Chat.content:type_name -> chat.v1.Content
	14, // 7: chat.v1.Chat.createdAt:type_name -> google.protobuf.Timestamp
	14, // 8: chat.v1.Chat.updatedAt:type_name -> google.protobuf.Timestamp
	4,  // 9: chat.v1.ListChatsResponse.chats:type_name -> chat.v1.Chat
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_chat_v1_model_proto_init() }
func file_chat_v1_model_proto_init() {
	if File_chat_v1_model_proto != nil {
		return
	}
	file_chat_v1_model_proto_msgTypes[0].OneofWrappers = []any{}
	file_chat_v1_model_proto_msgTypes[1].OneofWrappers = []any{}
	file_chat_v1_model_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_v1_model_proto_rawDesc), len(file_chat_v1_model_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_v1_model_proto_goTypes,
		DependencyIndexes: file_chat_v1_model_proto_depIdxs,
		EnumInfos:         file_chat_v1_model_proto_enumTypes,
		MessageInfos:      file_chat_v1_model_proto_msgTypes,
	}.Build()
	File_chat_v1_model_proto = out.File
	file_chat_v1_model_proto_goTypes = nil
	file_chat_v1_model_proto_depIdxs = nil
}
